#version 430 core

layout(local_size_x = 512, local_size_y = 1, local_size_z = 1) in;

struct Ray {
    vec3 pos;
    float rrel;
    vec3 dir;
    float reflectance;
    vec2 pos_apt;
    uint _pad[2];
};

struct Ghost {
    uint ray_offset;
    uint ray_count;
    uint tri_offset;
    uint tri_count;
};


uniform Params {
    uint wavelength_count;
    uint wavelength_sub_count;
    float min_area;
    float min_sliver;
};

uniform uint ghost_id;

layout(std430) buffer Ghosts {
    Ghost ghosts[];
};
layout(std430) buffer Rays {
    Ray rays[];
};
layout(std430) buffer Intensities {
    float intensities[];
};
layout(std430) buffer Indices {
    uint indices[];
};
layout(std430) buffer Counts {
    uint counts[];
};
layout(std430) buffer Mesh {
    uvec4 mesh[];
};
layout(std430) buffer Areas {
    float areas[];
};

float edge_function(vec2 a, vec2 b, vec2 c){
    return (a.x - b.x) * (c.y - a.y) - (a.y - b.y) * (c.x - a.x);
}

// Compute intensities per primitive per wavelength
void main() {
    uint tri_id = gl_GlobalInvocationID.x;

    uint ray_offset = ghosts[ghost_id].ray_offset;
    uint ray_count = ghosts[ghost_id].ray_count;
    uint tri_offset = ghosts[ghost_id].tri_offset;
    uint tri_count = ghosts[ghost_id].tri_count;

    if (tri_id >= tri_count) {
        return;
    }

    float relative_min_area = min_area * areas[ghost_id];

    uint invalid_prims = 0u;
    for (uint wavelength_id = 0u; wavelength_id < wavelength_count; ++wavelength_id) {
        uint tri_index = (tri_offset * wavelength_count) + (wavelength_id * tri_count) + tri_id;
        uint wavelength_ray_offset = (ray_offset * wavelength_count) + (wavelength_id * ray_count);

        Ray r[3];
        r[0] = rays[wavelength_ray_offset + mesh[tri_id].x];
        r[1] = rays[wavelength_ray_offset + mesh[tri_id].y];
        r[2] = rays[wavelength_ray_offset + mesh[tri_id].z];

        if (isinf(r[0].reflectance) || isinf(r[1].reflectance) || isinf(r[2].reflectance)) {
            return;
        }
        float intensity = 0;

        // Prevent super bright edges with min_area.
        vec2 pos0 = r[0].pos.xy;
        vec2 pos1 = r[1].pos.xy;
        vec2 pos2 = r[2].pos.xy;

        float area = abs(edge_function(pos0, pos1, pos2)) / 2.0;
        float area_safe = max(area, relative_min_area);
        intensity = area_safe > 0 ? areas[ghost_id] / area_safe : 0;

        //        // Darken slivers
        //        float a2 = dot(pos1 - pos0, pos1 - pos0);
        //        float b2 = dot(pos2 - pos1, pos2 - pos1);
        //        float c2 = dot(pos0 - pos2, pos0 - pos2);
        //        float min2 = min(a2, min(b2, c2));
        //        float max2 = max(a2, max(b2, c2));
        //
        //        float ratio = (max2 != 0.0) ? sqrt(min2 / max2) : 0;
        //        float sliver = smoothstep(0.3, 0.5, ratio);

        vec2 e1 = pos1 - pos0;
        vec2 e2 = pos2 - pos1;
        vec2 e3 = pos0 - pos2;

        float a2 = dot(e1, e1);
        float b2 = dot(e2, e2);
        float c2 = dot(e3, e3);
        float quality = (4 * sqrt(3) * area) / (a2 + b2 + c2);

        intensity *= smoothstep(clamp(min_sliver - 0.5, 0.0, 0.1), min_sliver, quality);

        intensities[tri_index] = intensity;

        // All rays are outside the housing.
        if (r[0].rrel > 1.0 && r[1].rrel > 1.0 && r[2].rrel > 1.0) {
            invalid_prims++;
        }
    }
    if (invalid_prims == wavelength_count) {
        // Cull the primitives where all wavelengths are outside the lens housing.
        return;
    }

    uint index_offset = tri_offset * 3u;
    uint offset = atomicAdd(counts[ghost_id], 3u);
    indices[index_offset + offset + 0] = mesh[tri_id].x;
    indices[index_offset + offset + 1] = mesh[tri_id].y;
    indices[index_offset + offset + 2] = mesh[tri_id].z;
}